export const API_KEY = "a1658cb202c24208b75623be12d1d249"
export const FETCH_SEARCHNEWS_REQUEST = 'FETCH_SEARCHNEWS_REQUEST'
export const FETCH_SEARCHNEWS_SUCCESS = 'FETCH_SEARCHNEWS_SUCCESS'
export const FETCH_SEARCHNEWS_FAILURE = 'FETCH_SEARCHNEWS_FAILURE'

export const FETCH_TOPNEWSHEADLINES_REQUEST = 'FETCH_TOPNEWSHEADLINES_REQUEST'
export const FETCH_TOPNEWSHEADLINES_SUCCESS = 'FETCH_TOPNEWSHEADLINES_SUCCESS'
export const FETCH_TOPNEWSHEADLINES_FAILURE = 'FETCH_TOPNEWSHEADLINES_FAILURE'

export const BOOKMARK_ITEM = 'BOOKMARK_ITEM';
export const UNBOOKMARK_ITEM = 'UNBOOKMARK_ITEM';
export const GET_BOOKMARK_ITEMS = 'GET_BOOKMARK_ITEMS';